# Generated by Django 5.1.8 on 2025-04-10 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0015_alter_accountservice_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationOneTimeToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_tokens', to='core.organization')),
            ],
            options={
                'verbose_name': 'Organization One Time Token',
                'verbose_name_plural': 'Organization One Time Tokens',
                'db_table': 'people_organization_one_time_token',
            },
        ),
    ]
