{{- if .Values.ports.smtp }}
apiVersion: v1
kind: Service
metadata:
  name: maildev-smtp
  labels:
    app: maildev
spec:
  type: ClusterIP
  ports:
    - name: smtp-{{ .Values.ports.smtp }}-tcp
      port: {{ .Values.ports.smtp }}
      protocol: TCP
      targetPort: {{ .Values.ports.smtp }}
  selector:
    app: maildev
{{- end }}
