# Generated by Django 6.0.6 on 2026-09-23 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailbox_oauth2', '0001_initial'),
        ('oauth2_provider', '0014_alter_help_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessToken',
        ),
        migrations.DeleteModel(
            name='Grant',
        ),
        migrations.DeleteModel(
            name='IDToken',
        ),
        migrations.DeleteModel(
            name='RefreshToken',
        ),
        migrations.RunSQL(
            sql="""
                DROP TABLE IF EXISTS oauth2_provider_application CASCADE;
                DROP TABLE IF EXISTS oauth2_provider_grant CASCADE;
                DROP TABLE IF EXISTS oauth2_provider_accesstoken CASCADE;
                DROP TABLE IF EXISTS oauth2_provider_refreshtoken CASCADE;
                DROP TABLE IF EXISTS oauth2_provider_idtoken CASCADE;
                DROP TABLE IF EXISTS oauth2_provider_devicegrant CASCADE;
            """,
        ),
    ]
