# Generated by Django 5.2.9 on 2026-02-04 14:19

import datetime
import django.contrib.postgres.fields
import django.db.models.deletion
import token_exchange.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0017_teamwebhook_protocol'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated at')),
                ('name', models.CharField(help_text="Unique identifier for this action scope, starts with 'action:'", max_length=255, unique=True, validators=[token_exchange.models.validate_action_scope_name], verbose_name='Action Name')),
                ('description', models.TextField(blank=True, help_text='Human-readable description of this action', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Action Scope',
                'verbose_name_plural': 'Action Scopes',
                'db_table': 'token_exchange_action_scope',
            },
        ),
        migrations.CreateModel(
            name='ExchangedToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated at')),
                ('token', models.CharField(db_index=True, help_text='The actual token string (opaque or JWT)', unique=True, verbose_name='Token')),
                ('token_type', models.CharField(choices=[('access_token', 'Access Token'), ('jwt', 'JWT')], default='access_token', help_text='The type of token as per RFC 8693', max_length=50, verbose_name='Token Type')),
                ('jwt_kid', models.CharField(blank=True, db_index=True, help_text='The key ID used to sign the JWT token', max_length=255, null=True, verbose_name='JWT Key ID')),
                ('subject_sub', models.CharField(blank=True, db_index=True, help_text='The subject identifier (sub) from the introspection', max_length=255, null=True, verbose_name='Subject Sub')),
                ('subject_email', models.EmailField(blank=True, db_index=True, help_text='The subject email from the introspection', max_length=255, null=True, verbose_name='Subject Email')),
                ('audiences', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, help_text='The audiences for this token (RFC 8693 supports multiple)', size=None, verbose_name='Audiences')),
                ('scope', models.TextField(blank=True, default='', help_text='Space-separated scopes for this token', verbose_name='Scope')),
                ('grants', models.JSONField(blank=True, default=list, help_text='List of grant objects with scope and throttling information', null=True, verbose_name='Grants')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When this token expires', verbose_name='Expires At')),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, help_text='When this token was revoked (null if not revoked)', null=True, verbose_name='Revoked At')),
                ('actor_token', models.TextField(blank=True, help_text='The actor token for delegation (RFC 8693)', null=True, verbose_name='Actor Token')),
                ('may_act', models.JSONField(blank=True, help_text='The may_act claim for delegation (RFC 8693)', null=True, verbose_name='May Act')),
                ('subject_token_jti', models.CharField(db_index=True, help_text='The JTI of the original SSO token for traceability', max_length=255, verbose_name='Subject Token JTI')),
                ('subject_token_scope', models.TextField(blank=True, default='', help_text='The original scopes from the SSO token', verbose_name='Subject Token Scope')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this token was created', verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Exchanged Token',
                'verbose_name_plural': 'Exchanged Tokens',
                'db_table': 'token_exchange_exchanged_token',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subject_sub', 'created_at'], name='token_excha_subject_633725_idx'), models.Index(fields=['subject_email', 'created_at'], name='token_excha_subject_c5c60f_idx'), models.Index(fields=['expires_at', 'revoked_at'], name='token_excha_expires_7f22e1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderCredentials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated at')),
                ('client_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Client ID')),
                ('client_secret', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Client secret')),
                ('allowed_origins', models.TextField(blank=True, default='', help_text='Allowed origins list to enable CORS, space separated')),
                ('is_active', models.BooleanField(default=True)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_exchange_credentials', to='core.serviceprovider')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TokenExchangeRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated at')),
                ('exchanged_token_duration', models.DurationField(blank=True, default=datetime.timedelta(seconds=300), help_text='Duration of the generated token')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('source_service', models.ForeignKey(help_text='Service provider initiating the token exchange', on_delete=django.db.models.deletion.CASCADE, related_name='exchange_out', to='core.serviceprovider', verbose_name='Source Service')),
                ('target_service', models.ForeignKey(help_text='Service provider receiving the exchanged token', on_delete=django.db.models.deletion.CASCADE, related_name='exchange_in', to='core.serviceprovider', verbose_name='Target Service')),
            ],
            options={
                'verbose_name': 'Token Exchange Rule',
                'verbose_name_plural': 'Token Exchange Rules',
                'db_table': 'token_exchange_rule',
                'unique_together': {('source_service', 'target_service')},
            },
        ),
        migrations.CreateModel(
            name='ActionScopeGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated at')),
                ('granted_scope', models.CharField(help_text='Scope granted on the target service when action is used', max_length=255, verbose_name='Granted Scope')),
                ('throttle_rate', models.CharField(blank=True, help_text="Optional throttle rate (e.g., '5/h', '100/day')", max_length=255, null=True, verbose_name='Throttle Rate')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='token_exchange.actionscope', verbose_name='Action Scope')),
                ('target_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_grants', to='core.serviceprovider', verbose_name='Target Service')),
            ],
            options={
                'verbose_name': 'Action Scope Grant',
                'verbose_name_plural': 'Action Scope Grants',
                'db_table': 'token_exchange_action_scope_grant',
                'unique_together': {('action', 'target_service', 'granted_scope')},
            },
        ),
        migrations.CreateModel(
            name='TokenExchangeActionPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated at')),
                ('required_source_scope', models.CharField(blank=True, help_text='Scope required in source token to use this action (empty = no requirement)', max_length=255, verbose_name='Required Source Scope')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='token_exchange.actionscope', verbose_name='Action Scope')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_permissions', to='token_exchange.tokenexchangerule', verbose_name='Exchange Rule')),
            ],
            options={
                'verbose_name': 'Token Exchange Action Permission',
                'verbose_name_plural': 'Token Exchange Action Permissions',
                'db_table': 'token_exchange_action_permission',
                'unique_together': {('rule', 'action')},
            },
        ),
        migrations.CreateModel(
            name='ScopeGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated at')),
                ('source_scope', models.CharField(help_text='Scope from the source token', max_length=255, verbose_name='Source Scope')),
                ('granted_scope', models.CharField(help_text='Scope granted on the target service', max_length=255, verbose_name='Granted Scope')),
                ('throttle_rate', models.CharField(blank=True, help_text="Optional throttle rate (e.g., '5/h', '100/day')", max_length=255, null=True, verbose_name='Throttle Rate')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_grants', to='token_exchange.tokenexchangerule', verbose_name='Exchange Rule')),
            ],
            options={
                'verbose_name': 'Scope Grant',
                'verbose_name_plural': 'Scope Grants',
                'db_table': 'token_exchange_scope_grant',
                'unique_together': {('rule', 'source_scope', 'granted_scope')},
            },
        ),
    ]
