{{- if .Values.mailcatcher.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mailcatcher
  labels:
    app: mailcatcher
spec:
  rules:
    - host: {{ .Values.mailcatcher.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mailcatcher
                port:
                  number: 1080
{{- end }}
