apiVersion: v1
kind: Service
metadata:
  name: mailcatcher
  labels:
    app: mailcatcher
spec:
  type: ClusterIP
  ports:
    - port: 1025
      targetPort: smtp
      protocol: TCP
      name: smtp
    - port: 1080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: mailcatcher
