# Generated by Django 5.1.5 on 2025-01-31 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailbox_manager', '0015_change_mailboxes_status_to_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailboxes', to='mailbox_manager.maildomain'),
        ),
    ]
