# Generated by Django 5.1.5 on 2025-02-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailbox_manager', '0016_alter_mailbox_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maildomain',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('enabled', 'Enabled'), ('failed', 'Failed'), ('disabled', 'Disabled'), ('action_required', 'Action required')], default='pending', max_length=20),
        ),
    ]
