# Generated by Django 5.1.5 on 2025-02-10 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_team_depth_team_numchild_team_path_and_more'),
        ('mailbox_manager', '0017_alter_maildomain_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='maildomain',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mail_domains', to='core.organization'),
        ),
    ]
