# Generated by Django 5.1.5 on 2025-02-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailbox_manager', '0018_maildomain_support_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='maildomain',
            name='last_check_details',
            field=models.JSONField(blank=True, help_text='A JSON object containing the last health check details', null=True, verbose_name='last check details'),
        ),
    ]
