# Generated by Django 5.1.6 on 2025-02-14 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailbox_manager', '0019_maildomain_last_check_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailbox',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mailbox', 'verbose_name_plural': 'Mailboxes'},
        ),
        migrations.AlterModelOptions(
            name='maildomain',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mail domain', 'verbose_name_plural': 'Mail domains'},
        ),
        migrations.AlterModelOptions(
            name='maildomainaccess',
            options={'ordering': ['-created_at'], 'verbose_name': 'User/mail domain relation', 'verbose_name_plural': 'User/mail domain relations'},
        ),
    ]
