# Generated by Django 5.1.6 on 2025-02-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailbox_manager', '0020_alter_mailbox_options_alter_maildomain_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maildomain',
            name='expected_config',
            field=models.JSONField(blank=True, help_text='A JSON object containing the expected config', null=True, verbose_name='expected config'),
        ),
    ]
