# Generated by Django 5.2.5 on 2025-09-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailbox_manager', '0025_alter_mailbox_secondary_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mailbox',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='mailbox',
            constraint=models.UniqueConstraint(fields=('local_part', 'domain'), name='unique_username'),
        ),
        migrations.AddConstraint(
            model_name='mailbox',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'domain'), name='unique_ox_display_name'),
        ),
    ]
