# Generated by Django 5.2.7 on 2025-10-21 15:49

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailbox_manager', '0026_alter_mailbox_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mailbox',
            name='unique_ox_display_name',
        ),
        migrations.AddConstraint(
            model_name='mailbox',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('first_name'), django.db.models.functions.text.Lower('last_name'), models.F('domain'), name='unique_ox_display_name', violation_error_message='Mailbox with this First name, Last name and Domain already exists.'),
        ),
    ]
