# Generated by Django 5.2.9 on 2025-12-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailbox_manager', '0028_alias'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alias',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='alias',
            constraint=models.UniqueConstraint(fields=('domain', 'local_part', 'destination'), name='no_duplicate'),
        ),
    ]
