# Generated by Django 6.0.3 on 2026-04-13 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailbox_manager', '0029_alter_alias_unique_together_alias_no_duplicate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailbox',
            options={'verbose_name': 'Mailbox', 'verbose_name_plural': 'Mailboxes'},
        ),
        migrations.RemoveConstraint(
            model_name='mailbox',
            name='unique_username',
        ),
    ]
