# Generated by Django 6.0.3 on 2026-04-13 13:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailbox_manager', '0030_alter_mailbox_options_remove_mailbox_unique_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionalMailbox',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated at')),
                ('local_part', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9_.-]+$')], verbose_name='local_part')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('enabled', 'Enabled'), ('failed', 'Failed'), ('disabled', 'Disabled')], default='pending', max_length=20)),
                ('dn_email', models.EmailField(blank=True, editable=False, max_length=254, unique=True, verbose_name='email')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functional_mailboxes', to='mailbox_manager.maildomain')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('local_part', 'domain'), name='unique_username')],
            },
        ),
    ]
