# Generated by Django 5.1.6 on 2025-02-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_team_depth_team_numchild_team_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='dn_vcard_data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
