# Generated by Django 5.1.7 on 2025-03-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_team_depth_team_numchild_team_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='A JSON object containing the organization metadata', verbose_name='metadata'),
        ),
    ]
