# Generated by Django 5.1.7 on 2025-03-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_team_depth_team_numchild_team_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_visible_all_services',
            field=models.BooleanField(default=False, help_text='Whether this team is visible to all service providers.', verbose_name='is visible for all SP'),
        ),
    ]
