# Generated by Django 5.1.8 on 2025-04-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_accountservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountservice',
            name='api_key',
            field=models.CharField(max_length=255, verbose_name='api key'),
        ),
    ]
