# Generated by Django 5.1.8 on 2025-04-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_team_external_id_alter_team_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamwebhook',
            name='protocol',
            field=models.CharField(choices=[('scim', 'Scim'), ('matrix', 'Matrix')], default='scim', max_length=10),
        ),
    ]
