# Generated by Django 5.2.3 on 2025-06-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_team_external_id_alter_team_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamwebhook',
            name='protocol',
            field=models.CharField(choices=[('scim', 'Scim'), ('matrix', 'Matrix')], default='scim'),
        ),
    ]
