name: Release Chart
run-name: Release Chart

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cleanup
        run: |
          rm -rf ./src/helm/extra
          rm -rf ./src/helm/dimail
          rm -rf ./src/helm/maildev

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Publish Helm charts
        uses: numerique-gouv/helm-gh-pages@add-overwrite-option
        with:
          charts_dir: ./src/helm
          linting: on
          token: ${{ secrets.GITHUB_TOKEN }}
